// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-charioteers.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/data.ts
var TOTAL_LAPS = 12;
var CHARIOTEERS = [
  { name: "Porphyrios", team: "blues", note: "Legendary Blue champion, the player's default mount." },
  { name: "Konstantinos", team: "blues", note: "Steady Blue driver who conserves stamina on the straights." },
  { name: "Theodoros", team: "blues", note: "Aggressive Blue driver, quick to spend boost." },
  { name: "Isaakios", team: "blues", note: "Blue tail-ender who thrives when rivals wreck." },
  { name: "Faustinus", team: "greens", note: "Green faction star, ruthless on the inside lane." },
  { name: "Anastasios", team: "greens", note: "Green tactician who saves stamina for late laps." },
  { name: "Belisarios", team: "greens", note: "Heavy-handed Green driver, frequent contact." },
  { name: "Mauricius", team: "greens", note: "Green rookie, erratic but fast." }
];
var CONTROLS = [
  { key: "Up arrow", action: "Crack the whip \u2014 short boost, drains stamina" },
  { key: "Down arrow", action: "Rein in the horses \u2014 slow down" },
  { key: "Left / Right arrows", action: "Change lane (smooth, accelerated steering)" },
  { key: "Mouse", action: "Look around from the driver's seat (FPS view)" },
  { key: "Esc / Exit", action: "Leave the race and return to team select" }
];
var MECHANICS = [
  "Each chariot is a quadriga: four horses abreast.",
  "12 laps of the Hippodrome; standings update live in the HUD and 2D minimap.",
  "Stamina drains while whipping. Yellow is safe; in the red the horses slow down.",
  "Boost has a cooldown and is also used by the AI charioteers.",
  "Every collision \u2014 chariot, wall, or wreck \u2014 costs hull integrity, with a cooldown so repeat contacts don't spiral.",
  "At 0 integrity the chariot is destroyed and is shown as DNF in the standings.",
  "AI uses rubber-banding to keep the race close and contested.",
  "Speed fluctuates continuously and drops slightly through corners and lane changes."
];
var HISTORY = [
  "The game is set in the Constantinople Hippodrome on the eve of the Nika riots (532 AD).",
  "The crowd is split between the Blue and Green factions, the great circus parties of Byzantium.",
  "The Kathisma is the imperial box overlooking the track.",
  "The spina down the middle carries obelisks and columns the chariots race around."
];

// src/lib/mcp/tools/list-charioteers.ts
var list_charioteers_default = defineTool({
  name: "list_charioteers",
  title: "List charioteers",
  description: "List the eight charioteers of the Hippodrome, optionally filtered by faction (Blues or Greens).",
  inputSchema: {
    team: z.enum(["blues", "greens", "all"]).optional().describe("Faction filter. Defaults to 'all'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ team }) => {
    const filter = team ?? "all";
    const rows = filter === "all" ? CHARIOTEERS : CHARIOTEERS.filter((c) => c.team === filter);
    const text = rows.map((c) => `${c.name} (${c.team}) \u2014 ${c.note}`).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { charioteers: rows }
    };
  }
});

// src/lib/mcp/tools/get-race-rules.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
var get_race_rules_default = defineTool2({
  name: "get_race_rules",
  title: "Get race rules and controls",
  description: "Explain how a race works: lap count, keyboard/mouse controls, stamina, boost, damage and DNF mechanics.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const text = [
      `Laps per race: ${TOTAL_LAPS}`,
      "",
      "Controls:",
      ...CONTROLS.map((c) => `- ${c.key}: ${c.action}`),
      "",
      "Mechanics:",
      ...MECHANICS.map((m) => `- ${m}`)
    ].join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { totalLaps: TOTAL_LAPS, controls: CONTROLS, mechanics: MECHANICS }
    };
  }
});

// src/lib/mcp/tools/get-hippodrome-lore.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
var get_hippodrome_lore_default = defineTool3({
  name: "get_hippodrome_lore",
  title: "Get Hippodrome lore",
  description: "Byzantine background for the game: the Hippodrome, the Blue/Green factions, and the Nika riots setting.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: HISTORY.map((h) => `- ${h}`).join("\n") }],
    structuredContent: { lore: HISTORY }
  })
});

// src/lib/mcp/tools/simulate-race.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var simulate_race_default = defineTool4({
  name: "simulate_race",
  title: "Simulate a race",
  description: "Run a quick offline simulation of a Hippodrome race and return the finishing order, including any wrecked (DNF) chariots.",
  inputSchema: {
    seed: z2.number().int().optional().describe("Optional integer seed for a reproducible result.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: ({ seed }) => {
    let s = (seed ?? Math.floor(Math.random() * 1e9)) >>> 0;
    const rand = () => {
      s = s * 1664525 + 1013904223 >>> 0;
      return s / 4294967296;
    };
    const results = CHARIOTEERS.map((c) => {
      const pace = 0.85 + rand() * 0.3;
      const wrecked = rand() < 0.12;
      const laps = wrecked ? 1 + Math.floor(rand() * (TOTAL_LAPS - 1)) : TOTAL_LAPS;
      const time = wrecked ? Infinity : Math.round(TOTAL_LAPS * 24 / pace);
      return { ...c, wrecked, laps, timeSeconds: wrecked ? null : time, _time: time };
    }).sort((a, b) => a._time - b._time);
    const text = results.map(
      (r, i) => r.wrecked ? `DNF \u2014 ${r.name} (${r.team}), wrecked on lap ${r.laps}` : `${i + 1}. ${r.name} (${r.team}) \u2014 ${r.timeSeconds}s`
    ).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        seed: seed ?? null,
        standings: results.map(({ _time, note, ...r }) => r)
      }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "byzantine-chariot-racing",
  title: "Byzantine Chariot Racing",
  version: "0.1.0",
  instructions: "Tools for the Byzantine Chariot Racing game set in the Constantinople Hippodrome. Use `list_charioteers` for the Blue and Green drivers, `get_race_rules` for controls and mechanics, `get_hippodrome_lore` for historical background, and `simulate_race` to generate an example race result.",
  tools: [list_charioteers_default, get_race_rules_default, get_hippodrome_lore_default, simulate_race_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
